[package]
name = "run-here"
version = "0.2.0"
edition = "2021"

[dependencies]
multimap = "0.8.3"
procfs = "0.12.0"
swayipc = "3.0.1"
exec = "0.3.1"
thiserror = "1.0"
anyhow = "1.0"
errno = "0.2.8"
clap = { version = "4.0.18", features = ["derive"] }
users = "0.11.0"
